name: 'mirror repository'

on:
  push:
    branches: [main]
  delete:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  mirror_repo:
    runs-on: [self-hosted]
    steps:
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"
